### ISSUE TITLE
 The system cannot find the file specified.

### ISSUE THREAD

**Issue by pandason125** [wailsapp/go-webview2#18]
when the app run a moment or open a new windows may be prompt “ The system cannot find the file specified.”and exit

**Comment by pandason125** [comment]
the err postion code:
func (i *ICoreWebView2Controller) MoveFocus(reason COREWEBVIEW2_MOVE_FOCUS_REASON) error {
	var err error

	_, _, err = i.vtbl.MoveFocus.Call(
		uintptr(unsafe.Pointer(i)),
		uintptr(reason),
	)
	if err != windows.ERROR_SUCCESS {
		return err
	}
	return nil
}

**Comment by pandason125** [comment]
may be must modify it like this:

func (i *ICoreWebView2Controller) MoveFocus(reason COREWEBVIEW2_MOVE_FOCUS_REASON) error {
	var err error

	_, _, err = i.vtbl.MoveFocus.Call(
		uintptr(unsafe.Pointer(i)),
		uintptr(unsafe.Pointer(&reason)),//get adress
	)
	if err != windows.ERROR_SUCCESS {
		
		return err
	}
	return nil
}

**Comment by pandason125** [comment]
<img width="83" alt="微信图片_20240905152148" src="https://github.com/user-attachments/assets/9c69d575-66c7-4877-a01c-7de1443687d3">
when other window can not eject from system Taskbar ，code is triggering this bug

**Comment by leaanthony** [comment]
Thanks for reporting. Fixed 👍
