### ISSUE TITLE
Should we consider printing error stack information when the process exits?

### ISSUE THREAD

**Issue by Tianxidev** [wailsapp/go-webview2#22]
Should we consider printing error stack information when the process exits?

**File:**  github.com\wailsapp\go-webview2\pkg\edge\chromium.go
**Line:** 114-117

``` go
func (e *Chromium) errorCallback(err error) {
	e.globalErrorCallback(err)
	os.Exit(1)
}
```

**Comment by leaanthony** [comment]
Good idea! Feel free to open a PR 🙏
