### ISSUE TITLE
Long string callback will make "Overlapped I/O operation is in progress" panic of v1.0.11

### ISSUE THREAD

**Issue by rakirizu** [wailsapp/go-webview2#8]
Hello, after I updated go-webview to v1.0.11, when calling Golang through JS to return a long string, a panic: `Overlapped I/O operation is in progress.` will appear.

(it case `goroutine stack exceeds 1000000000-byte limit` before I fix #6)

Test Project: [myproject.zip](https://github.com/user-attachments/files/16500739/myproject.zip)
this project is created by `wails init -n myproject -t vue-ts`, and run `go get -u`
It works fine after I changed `github.com/wailsapp/go-webview2 v1.0.11` to `github.com/wailsapp/go-webview2 v1.0.10` .

---

wails doctor: 

![QQ20240806-011454](https://github.com/user-attachments/assets/0f961b95-98b7-4764-a2b2-e7e2f5743714)

panic:

![QQ20240806-011038](https://github.com/user-attachments/assets/660a8315-030b-4818-a548-805d2a7ece22)

**Comment by lanyeeee** [comment]
I also encountered this issue after updating to v1.0.11. The situation is exactly as you described.

**Comment by leaanthony** [comment]
Fixed on master: https://github.com/wailsapp/go-webview2/pull/7
